version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service
    container_name: ewm-stats
    ports:
      - "9090:9090"
    expose:
      - 9090
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_stats_db:5433/ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 9090

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - 5433:5433
    expose:
      - 5433
    volumes:
      - vol-stats-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 5433

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_service_db:5434/main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATSERV_URL=http://ewm-stats:9090
    command:
      - p 8080

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_service_db
    ports:
      - 5434:5434
    expose:
      - 5434
    volumes:
      - vol-ewm-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command:
      -p 5434

volumes:
  vol-ewm-db:
  vol-stats-db: