DROP TABLE IF EXISTS statistics CASCADE;

create sequence statistics_id_seq;

CREATE TABLE IF NOT EXISTS statistics
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    app         VARCHAR(256)                            NOT NULL,
    uri         VARCHAR(3000)                           NOT NULL,
    ip          VARCHAR(256)                            NOT NULL,
    date_create TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);